FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
MAINTAINER WoongJae <skydnd0304@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y \
		build-essential \
		ca-certificates \
		gcc \
		git \
		libpq-dev \
		make \
		python-pip \
		python2.7 \
		python2.7-dev && \
	apt-get autoremove && \
	apt-get clean

RUN apt-get install -y \
	libglib2.0-0 \
	libsm6 \
	libxext6 \
	libxrender-dev

RUN pip install --upgrade pip

COPY req.txt /home/
WORKDIR /home/
RUN pip install -r req.txt
