FROM ailispaw/barge:armhf

RUN pkg install mjpg-streamer

EXPOSE 8080

ENTRYPOINT [ "dumb-init", "--", "mjpg_streamer" ]

CMD [ "-i", "input_uvc.so", "-d", "/dev/video0", "-r", "640x480", "-f", "20", "-o", "output_http.so -w /usr/www -p 8080" ]